package practices.projecteulernetproblem;

public class P002_EvenFibonacciNumbers {
    public static void main(String[] args) {
        fibonacciNumbers();

    }
    /*
    Even Fibonacci numbers
    Problem 2
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    */
    /*
    Çift Fibonacci sayıları
    Soru : 2
    Fibonacci dizisindeki her yeni terim, önceki iki terimin eklenmesiyle oluşturulur.
    1 ve 2 ile başlayarak ilk 10 terim şöyle olacaktır:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    Değerleri dört milyonu geçmeyen Fibonacci dizisindeki terimleri dikkate alarak,
    çift değerli terimlerin toplamını bulunuz.
    */
    public static void fibonacciNumbers(){
        int numberLimit = 100;
        int numberOne = 1;
        int numberTwo = 2;
        int numberThree = 3;
        int sum = 2;
        System.out.println(numberOne + "\n" + numberTwo + "\n" + numberThree);
        for (int i = 4; i < numberLimit ; i++) {
            numberOne = numberTwo;
            numberTwo = numberThree;
            numberThree = numberOne + numberTwo;
            if (numberThree % 2 == 0) {
                sum += numberThree;
            }
            System.out.println(numberThree);
        }
        System.out.println("Toplam : " + sum);
    }
}
